config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Core::FindTodo.find_all
  end

  def new
  end

  def create
    Core::CreateTodo.create(params[:content])
    redirect_to todos_path
  end

  def destroy
    Core::DestroyTodo.destroy(params[:id].to_i)
    redirect_to todos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Todos</h1>

<%= link_to 'Add', new_todo_path %>
<ul>
  <% @todos.each do |todo| %>
    <li>
      <span><%= todo.content %></span>
      <span><%= link_to "delete", todo_path(todo.id), method: :delete %></span>
    </li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h1>Add Todo</h1>

<%= form_tag todos_path, method: :post do %>
  <input type="text" name="content" />
  <input type="submit" />
<% end %>